/* const data={
    A: ["Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan"],
    B: ["Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
       "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia",
        "Botswana",
       "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi"],
    C:["Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo, Democratic Republic of the",
        "Congo, Republic of the Costa Rica",
        "Côte d’Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic"],
    D:["Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic"],
    E:["East Timor (Timor-Leste)",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia"],
    F:["Fiji",
        "Finland",
        "France"],
    G:["Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana"],
    H:["Haiti",
        "Honduras",
        "Hungary"],
    I:["Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy"
        ],
    J:["Jamaica",
        "Japan",
        "Jordan"],
    K:["Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, North",
        "Korea, South",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",],
    L:[
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg"],
    M:["Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        ],
    N:["Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand"],
    O:["Oman"],
    P:["Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",],
    Q:["Qatar"],
    R:["Romania",
        "Russia",
        "Rwanda"],
    S:["Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia"],
    T:["Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga"],
    U:["Uganda",
        "Ukraine",
       " United Arab Emirates",
        "United Kingdom"],
    V:["Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam"],
    Y:["Yemen"],
    Z:["Zambia",
        "Zimbabwe"]
} */
 const data=[
    "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
       "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia",
        "Botswana",
       "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo, Democratic Republic of the",
        "Congo, Republic of the Costa Rica",
        "Côte d'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "East Timor (Timor-Leste)",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
    "Haiti",
        "Honduras",
        "Hungary",
    "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy"
        ,
    "Jamaica",
        "Japan",
        "Jordan",
    "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, North",
        "Korea, South",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
    
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
    "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        
    "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
    "Oman",
    "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
    "Qatar",
    "Romania",
        "Russia",
        "Rwanda",
    "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
    "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga",
    "Uganda",
        "Ukraine",
       " United Arab Emirates",
        "United Kingdom",
    "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
    "Yemen",
    "Zambia",
        "Zimbabwe"
]
export default data;